# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agression',
            field=models.BooleanField(default=False),
        ),
    ]
