# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_userprofile_agression'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='attackCost',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
