# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_weapon_attackcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultIa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
            ],
        ),
    ]
