# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20161129_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultia',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='typeitem',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
