# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_battlehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dev',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='exp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='srch',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
