# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlehistory',
            name='opp_used_script',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.Ia'),
        ),
        migrations.AddField(
            model_name='battlehistory',
            name='used_script',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backend.Ia'),
        ),
        migrations.AddField(
            model_name='ia',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
