# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20171115_1446'),
        ('backend', '0009_userprofile_level'),
    ]

    operations = [
    ]
