# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20171125_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlehistory',
            name='opponent_x',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battlehistory',
            name='opponent_y',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battlehistory',
            name='player_x',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battlehistory',
            name='player_y',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
