# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20171126_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlehistory',
            name='map_name',
            field=models.CharField(default='terre', max_length=10),
        ),
    ]
