# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_userprofile_true_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='next_level_exp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
