# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-16 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20171129_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to='img/user_avatar'),
        ),
    ]
