# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-26 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20180416_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlehistory',
            name='mode',
            field=models.BooleanField(default=False),
        ),
    ]
