# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-27 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_battlehistory_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('players', models.ManyToManyField(to='backend.UserProfile')),
            ],
        ),
    ]
