# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-01 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_championship'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlehistory',
            name='championship_name',
            field=models.CharField(default='Championnat PyRobot [Default]', max_length=60),
        ),
    ]
