# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-10 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_auto_20180503_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='private_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='championship',
            name='secret_word',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
