# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-22 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_auto_20180510_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='dev',
            new_name='nb_games',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='exp',
            new_name='points',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='srch',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='coeff_K',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='battlehistory',
            name='championship_name',
            field=models.CharField(default='PyRobot [Default]', max_length=60),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='img/user_avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='next_level_exp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
