# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-23 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_auto_20180523_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='ia',
            name='edit',
            field=models.BooleanField(default=False),
        ),
    ]
